bls:
  metadata:
    bq_project: 'turnkey-clover-480017-b8'
    bq_dataset: 'metadata'
    bq_table: 'bls_section_files'
  timeseries:
    base_url: 'https://download.bls.gov/pub/time.series'
    storage_bkt: 'rearc-soln'
    pr:
      files_to_skip: 
        - '[To Parent Directory]'
api:
  datausa:
    storage_bkt: 'rearc-soln' 
    honolulu:
      base_url: 'https://honolulu-api.datausa.io'
      resource_path: 'tesseract/data.jsonrecords'
      query_params:
        drilldowns:
          - 'Year'
          - 'Nation'
        cube: 'acs_yg_total_population_1'
        locale: 'en'
        measures: 'Population'
