bls:
  metadata:
    bq_project: '<pid>'
    bq_dataset: 'metadata'
    bq_table: 'bls_section_files'
  timeseries:
    base_url: 'https://download.bls.gov/pub/time.series'
    storage_bkt: 'rearc-soln'
    pr:
      files_to_skip: 
        - '[To Parent Directory]'
api:
  datausa:
    storage_bkt: 'rearc-soln' 
    honolulu:
      base_url: 'https://honolulu-api.datausa.io'
      resource_path: 'tesseract/data.jsonrecords'
      query_params:
        drilldowns:
          - 'Year'
          - 'Nation'
        cube: 'acs_yg_total_population_1'
        locale: 'en'
        measures: 'Population'
event:
  storage_bkt: 'rearc-soln'
  bls:
    metadata:
      pr:
        pr.data.0.Current:
          sep: '\t'
          columns:
            - series_id
            - year
            - period 
            - value 
            - footnote_codes
  datausa:
    honululu:
      file: 'cube_acs_yg_total_population_data'
      columns:
        - nation_id
        - nation
        - year
        - population
